"""add soft delete to blogs

Revision ID: 521bc6f5a63b
Revises: 9c9630e74e3d
Create Date: 2026-01-09 17:26:24.492538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521bc6f5a63b'
down_revision: Union[str, None] = '9c9630e74e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.drop_index('ix_blogs_id', table_name='blogs')
    op.drop_constraint('blogs_author_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_author_id_fkey', 'blogs', 'users', ['author_id'], ['id'])
    op.create_index('ix_blogs_id', 'blogs', ['id'], unique=False)
    op.drop_column('blogs', 'is_deleted')
    # ### end Alembic commands ###
