"""add recommendation tables

Revision ID: a1b2c3d4e5f6
Revises: 9f1d2c3b4a56
Create Date: 2026-01-22 05:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '9f1d2c3b4a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blog_keywords_blog_id', 'blog_keywords', ['blog_id'], unique=False)
    op.create_index('ix_blog_keywords_id', 'blog_keywords', ['id'], unique=False)
    op.create_index('ix_blog_keywords_keyword', 'blog_keywords', ['keyword'], unique=False)
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_index('ix_blog_vectors_id', 'blog_vectors', ['id'], unique=False)
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_keywords_id', 'user_keywords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_keywords_id', table_name='user_keywords')
    op.drop_table('user_keywords')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_vectors_id', table_name='blog_vectors')
    op.drop_table('blog_vectors')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_keywords_keyword', table_name='blog_keywords')
    op.drop_index('ix_blog_keywords_id', table_name='blog_keywords')
    op.drop_index('ix_blog_keywords_blog_id', table_name='blog_keywords')
    op.drop_table('blog_keywords')
    # ### end Alembic commands ###